CREATE TABLE customers (
    customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100),
    email VARCHAR2(100),
    phone VARCHAR2(15),
    created_at DATE DEFAULT SYSDATE
);

CREATE TABLE accounts (
    account_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id NUMBER,
    account_type VARCHAR2(20),
    balance NUMBER(12,2) DEFAULT 0,
    created_at DATE DEFAULT SYSDATE,
    
    CONSTRAINT fk_customer
    FOREIGN KEY (customer_id)
    REFERENCES customers(customer_id)
);

CREATE TABLE transactions (
    transaction_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id NUMBER,
    transaction_type VARCHAR2(20),
    amount NUMBER(12,2),
    transaction_date DATE DEFAULT SYSDATE,
    status VARCHAR2(20),
    
    CONSTRAINT fk_account
    FOREIGN KEY (account_id)
    REFERENCES accounts(account_id)
);

CREATE TABLE kyc_documents (
    kyc_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id NUMBER,
    document_type VARCHAR2(50),

    -- 🔥 All 3 types
    document_blob BLOB,         -- store file inside DB
    document_clob CLOB,         -- store large text (description/log)
    document_bfile BFILE,       -- external file reference

    uploaded_at DATE DEFAULT SYSDATE,

    CONSTRAINT fk_kyc_customer
    FOREIGN KEY (customer_id)
    REFERENCES customers(customer_id)
);

CREATE TABLE audit_logs (
    log_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action_type VARCHAR2(50),
    description CLOB,
    created_at DATE DEFAULT SYSDATE
);

SELECT table_name FROM user_tables;

CREATE OR REPLACE FUNCTION get_balance(p_account_id NUMBER)
RETURN NUMBER
IS
    v_balance NUMBER;
BEGIN
    SELECT balance INTO v_balance
    FROM accounts
    WHERE account_id = p_account_id;

    RETURN v_balance;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 0;
END;
/

CREATE OR REPLACE PROCEDURE process_transaction (
    p_account_id NUMBER,
    p_type VARCHAR2,
    p_amount NUMBER
)
IS
    v_balance NUMBER;

    insufficient_funds EXCEPTION;
BEGIN
    -- Get current balance
    v_balance := get_balance(p_account_id);

    -- Check withdrawal
    IF p_type = 'WITHDRAW' AND v_balance < p_amount THEN
        RAISE insufficient_funds;
    END IF;

    -- Insert transaction
    INSERT INTO transactions (
        account_id,
        transaction_type,
        amount,
        status
    )
    VALUES (
        p_account_id,
        p_type,
        p_amount,
        'SUCCESS'
    );

EXCEPTION
    WHEN insufficient_funds THEN
        INSERT INTO transactions (
            account_id,
            transaction_type,
            amount,
            status
        )
        VALUES (
            p_account_id,
            p_type,
            p_amount,
            'FAILED'
        );

        DBMS_OUTPUT.PUT_LINE('Insufficient funds');

    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error occurred');
END;
/

CREATE OR REPLACE TRIGGER trg_update_balance
AFTER INSERT ON transactions
FOR EACH ROW
BEGIN
    IF :NEW.transaction_type = 'DEPOSIT' AND :NEW.status = 'SUCCESS' THEN
        UPDATE accounts
        SET balance = balance + :NEW.amount
        WHERE account_id = :NEW.account_id;

    ELSIF :NEW.transaction_type = 'WITHDRAW' AND :NEW.status = 'SUCCESS' THEN
        UPDATE accounts
        SET balance = balance - :NEW.amount
        WHERE account_id = :NEW.account_id;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_audit_log
AFTER INSERT ON transactions
FOR EACH ROW
BEGIN
    INSERT INTO audit_logs (
        action_type,
        description
    )
    VALUES (
        'TRANSACTION',
        'Transaction ID: ' || :NEW.transaction_id ||
        ', Type: ' || :NEW.transaction_type ||
        ', Amount: ' || :NEW.amount
    );
END;
/

INSERT INTO customers (name, email, phone)
VALUES ('John Doe', 'john@example.com', '9876543210');

INSERT INTO accounts (customer_id, account_type, balance)
VALUES (1, 'Savings', 5000);

COMMIT;

BEGIN
    process_transaction(2, 'DEPOSIT', 60000);
END;
/

BEGIN
    process_transaction(2, 'DEPOSIT', 1000);
END;
/

BEGIN
    process_transaction(2, 'DEPOSIT', 2000);
END;
/

BEGIN
    process_transaction(2, 'DEPOSIT', 3000);
END;
/

BEGIN
    process_transaction(2, 'DEPOSIT', 4000);
END;
/

commit;

select * from transactions;